# Generated by Django 5.0.14 on 2025-11-22 20:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birthdays_enabled', models.BooleanField(default=True, verbose_name='birthday notifications')),
                ('achievements_enabled', models.BooleanField(default=True, verbose_name='achievement notifications')),
                ('news_enabled', models.BooleanField(default=True, verbose_name='news notifications')),
                ('comments_enabled', models.BooleanField(default=True, verbose_name='comment notifications')),
                ('reactions_enabled', models.BooleanField(default=True, verbose_name='reaction notifications')),
                ('email_enabled', models.BooleanField(default=False, verbose_name='email notifications')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_settings', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'notification settings',
                'verbose_name_plural': 'notification settings',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('birthday', 'Birthday'), ('achievement', 'Achievement'), ('news', 'News'), ('comment', 'Comment'), ('reaction', 'Reaction'), ('system', 'System')], max_length=20, verbose_name='type')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('message', models.TextField(verbose_name='message')),
                ('link', models.CharField(blank=True, max_length=500, verbose_name='link')),
                ('is_read', models.BooleanField(default=False, verbose_name='read')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('related_object_type', models.CharField(blank=True, max_length=50, verbose_name='related object type')),
                ('related_object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='related object id')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'notification',
                'verbose_name_plural': 'notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read'], name='notificatio_user_id_427e4b_idx'), models.Index(fields=['user', 'created_at'], name='notificatio_user_id_c62b26_idx')],
            },
        ),
    ]
