# Generated by Django 5.0.14 on 2025-11-24 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='is_admin',
            field=models.BooleanField(default=False, help_text='Roles with full administrative access', verbose_name='admin role'),
        ),
    ]
