# Generated by Django 5.0.14 on 2025-11-27 19:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0001_initial'),
        ('roles', '0002_add_is_admin_field'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WikiTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='URL-имя')),
                ('color', models.CharField(default='blue', max_length=20, verbose_name='Цвет')),
            ],
            options={
                'verbose_name': 'Тег Wiki',
                'verbose_name_plural': 'Теги Wiki',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WikiPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Заголовок')),
                ('slug', models.SlugField(max_length=300, verbose_name='URL-имя')),
                ('content', models.JSONField(blank=True, default=dict, verbose_name='Содержимое')),
                ('excerpt', models.TextField(blank=True, max_length=500, verbose_name='Краткое описание')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('depth', models.PositiveIntegerField(default=0, verbose_name='Глубина вложенности')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('is_archived', models.BooleanField(default=False, verbose_name='В архиве')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='Просмотры')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wiki_pages', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='wiki.wikipage', verbose_name='Родительская страница')),
            ],
            options={
                'verbose_name': 'Страница Wiki',
                'verbose_name_plural': 'Страницы Wiki',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='WikiAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='wiki/attachments/%Y/%m/', verbose_name='Файл')),
                ('filename', models.CharField(max_length=255, verbose_name='Имя файла')),
                ('size', models.PositiveIntegerField(default=0, verbose_name='Размер (байт)')),
                ('mime_type', models.CharField(blank=True, max_length=100, verbose_name='MIME тип')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wiki_attachments', to=settings.AUTH_USER_MODEL, verbose_name='Загружено')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='wiki.wikipage', verbose_name='Страница')),
            ],
            options={
                'verbose_name': 'Вложение Wiki',
                'verbose_name_plural': 'Вложения Wiki',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WikiSpace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='URL-имя')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('icon', models.CharField(default='Folder', max_length=50, verbose_name='Иконка')),
                ('is_public', models.BooleanField(default=True, verbose_name='Публичный доступ')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('allowed_departments', models.ManyToManyField(blank=True, related_name='accessible_wiki_spaces', to='organization.department', verbose_name='Доступные отделы')),
                ('allowed_roles', models.ManyToManyField(blank=True, related_name='accessible_wiki_spaces', to='roles.role', verbose_name='Доступные роли')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wiki_spaces', to='organization.department', verbose_name='Отдел')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_wiki_spaces', to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Пространство Wiki',
                'verbose_name_plural': 'Пространства Wiki',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='wikipage',
            name='space',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='wiki.wikispace', verbose_name='Пространство'),
        ),
        migrations.AddField(
            model_name='wikipage',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='pages', to='wiki.wikitag', verbose_name='Теги'),
        ),
        migrations.CreateModel(
            name='WikiPageVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.PositiveIntegerField(verbose_name='Номер версии')),
                ('content', models.JSONField(default=dict, verbose_name='Содержимое')),
                ('title', models.CharField(max_length=300, verbose_name='Заголовок')),
                ('change_summary', models.CharField(blank=True, max_length=500, verbose_name='Описание изменений')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wiki_page_versions', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='wiki.wikipage', verbose_name='Страница')),
            ],
            options={
                'verbose_name': 'Версия страницы Wiki',
                'verbose_name_plural': 'Версии страниц Wiki',
                'ordering': ['-version_number'],
                'unique_together': {('page', 'version_number')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='wikipage',
            unique_together={('space', 'slug')},
        ),
    ]
