# Generated by Django 5.0.14 on 2025-11-22 20:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('login', 'Login'), ('logout', 'Logout'), ('archive', 'Archive'), ('restore', 'Restore'), ('password_change', 'Password Change'), ('password_reset', 'Password Reset')], max_length=20, verbose_name='action')),
                ('entity_type', models.CharField(help_text='Model name (e.g., User, News)', max_length=100, verbose_name='entity type')),
                ('entity_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='entity id')),
                ('entity_repr', models.CharField(blank=True, help_text='String representation of the entity', max_length=255, verbose_name='entity representation')),
                ('old_values', models.JSONField(blank=True, null=True, verbose_name='old values')),
                ('new_values', models.JSONField(blank=True, null=True, verbose_name='new values')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP address')),
                ('user_agent', models.TextField(blank=True, verbose_name='user agent')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'audit log',
                'verbose_name_plural': 'audit logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['entity_type', 'entity_id'], name='audit_audit_entity__9535bf_idx'), models.Index(fields=['user', 'created_at'], name='audit_audit_user_id_a3c2bc_idx'), models.Index(fields=['action', 'created_at'], name='audit_audit_action_766c6d_idx')],
            },
        ),
    ]
