# Generated by Django 5.0.14 on 2025-11-22 20:50

import core.utils
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('description', models.TextField(verbose_name='description')),
                ('icon', models.ImageField(upload_to=core.utils.achievement_icon_upload_path, verbose_name='icon')),
                ('category', models.CharField(choices=[('professional', 'Professional'), ('corporate', 'Corporate'), ('social', 'Social'), ('special', 'Special')], default='professional', max_length=20, verbose_name='category')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_achievements', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
            ],
            options={
                'verbose_name': 'achievement',
                'verbose_name_plural': 'achievements',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AchievementAward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(help_text='Reason for awarding this achievement', verbose_name='comment')),
                ('awarded_at', models.DateTimeField(auto_now_add=True, verbose_name='awarded at')),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awards', to='achievements.achievement', verbose_name='achievement')),
                ('awarded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='given_achievements', to=settings.AUTH_USER_MODEL, verbose_name='awarded by')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_achievements', to=settings.AUTH_USER_MODEL, verbose_name='recipient')),
            ],
            options={
                'verbose_name': 'achievement award',
                'verbose_name_plural': 'achievement awards',
                'ordering': ['-awarded_at'],
            },
        ),
    ]
