# Generated by Django 5.0.14 on 2025-11-22 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='icon',
            field=models.CharField(default='🏆', help_text='Emoji icon for the achievement', max_length=10, verbose_name='icon'),
        ),
    ]
