# Generated by Django 5.0.14 on 2025-11-25 16:27

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KeyResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('type', models.CharField(choices=[('quantitative', 'Количественный'), ('qualitative', 'Качественный')], default='quantitative', max_length=20, verbose_name='Тип')),
                ('target_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Целевое значение')),
                ('current_value', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Текущее значение')),
                ('start_value', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Начальное значение')),
                ('unit', models.CharField(blank=True, default='', max_length=50, verbose_name='Единица измерения')),
                ('progress', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Прогресс %')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
            ],
            options={
                'verbose_name': 'Ключевой результат',
                'verbose_name_plural': 'Ключевые результаты',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='OKRPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('type', models.CharField(choices=[('quarter', 'Квартал'), ('year', 'Год')], default='quarter', max_length=10, verbose_name='Тип периода')),
                ('starts_at', models.DateField(verbose_name='Дата начала')),
                ('ends_at', models.DateField(verbose_name='Дата окончания')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
            ],
            options={
                'verbose_name': 'Период OKR',
                'verbose_name_plural': 'Периоды OKR',
                'ordering': ['-starts_at'],
            },
        ),
        migrations.CreateModel(
            name='CheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Предыдущее значение')),
                ('new_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Новое значение')),
                ('previous_progress', models.IntegerField(default=0, verbose_name='Предыдущий прогресс %')),
                ('new_progress', models.IntegerField(default=0, verbose_name='Новый прогресс %')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='okr_check_ins', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('key_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='check_ins', to='okr.keyresult', verbose_name='Ключевой результат')),
            ],
            options={
                'verbose_name': 'Check-in',
                'verbose_name_plural': 'Check-ins',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Objective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('level', models.CharField(choices=[('company', 'Компания'), ('department', 'Отдел'), ('personal', 'Личная')], default='personal', max_length=20, verbose_name='Уровень')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('active', 'Активна'), ('completed', 'Завершена'), ('cancelled', 'Отменена')], default='draft', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлена')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='objectives', to='organization.department', verbose_name='Отдел')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objectives', to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='okr.objective', verbose_name='Родительская цель')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objectives', to='okr.okrperiod', verbose_name='Период')),
            ],
            options={
                'verbose_name': 'Цель',
                'verbose_name_plural': 'Цели',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='keyresult',
            name='objective',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='key_results', to='okr.objective', verbose_name='Цель'),
        ),
    ]
