# Generated by Django 5.0.14 on 2025-11-22 20:50

import core.utils
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('first_name', models.CharField(max_length=50, verbose_name='first name')),
                ('last_name', models.CharField(max_length=50, verbose_name='last name')),
                ('patronymic', models.CharField(blank=True, max_length=50, verbose_name='patronymic')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to=core.utils.avatar_upload_path, verbose_name='avatar')),
                ('phone_work', models.CharField(blank=True, max_length=20, verbose_name='work phone')),
                ('phone_personal', models.CharField(blank=True, max_length=20, verbose_name='personal phone')),
                ('telegram', models.CharField(blank=True, max_length=50, verbose_name='telegram')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='birth date')),
                ('hire_date', models.DateField(blank=True, null=True, verbose_name='hire date')),
                ('is_archived', models.BooleanField(default=False, verbose_name='archived')),
                ('archived_at', models.DateTimeField(blank=True, null=True, verbose_name='archived at')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='UserStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('vacation', 'Vacation'), ('sick_leave', 'Sick Leave'), ('business_trip', 'Business Trip'), ('remote', 'Remote Work'), ('maternity', 'Maternity Leave')], max_length=20, verbose_name='status')),
                ('start_date', models.DateField(verbose_name='start date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='end date')),
                ('comment', models.TextField(blank=True, verbose_name='comment')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
            ],
            options={
                'verbose_name': 'user status',
                'verbose_name_plural': 'user statuses',
                'ordering': ['-start_date'],
            },
        ),
    ]
