# Generated by Django 5.0.14 on 2025-11-25 18:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwoFactorSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=False, verbose_name='2FA enabled')),
                ('secret', models.CharField(blank=True, help_text='Base32 encoded secret key', max_length=32, verbose_name='TOTP secret')),
                ('backup_codes', models.JSONField(blank=True, default=list, help_text='Hashed backup codes', verbose_name='backup codes')),
                ('enabled_at', models.DateTimeField(blank=True, null=True, verbose_name='enabled at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='two_factor_settings', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'two-factor settings',
                'verbose_name_plural': 'two-factor settings',
            },
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_jti', models.CharField(help_text='JWT token identifier', max_length=255, unique=True, verbose_name='token JTI')),
                ('device_type', models.CharField(blank=True, max_length=50, verbose_name='device type')),
                ('device_name', models.CharField(blank=True, max_length=100, verbose_name='device name')),
                ('browser', models.CharField(blank=True, max_length=100, verbose_name='browser')),
                ('os', models.CharField(blank=True, max_length=100, verbose_name='operating system')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP address')),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='location')),
                ('user_agent', models.TextField(blank=True, verbose_name='user agent')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('last_activity', models.DateTimeField(auto_now=True, verbose_name='last activity')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'user session',
                'verbose_name_plural': 'user sessions',
                'ordering': ['-last_activity'],
            },
        ),
    ]
