# Generated by Django 5.0.14 on 2025-11-25 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_add_2fa_and_sessions'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersession',
            name='access_jti',
            field=models.CharField(blank=True, help_text='Access JWT token identifier for session detection', max_length=255, verbose_name='access token JTI'),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='token_jti',
            field=models.CharField(help_text='Refresh JWT token identifier for blacklisting', max_length=255, unique=True, verbose_name='refresh token JTI'),
        ),
    ]
