# Generated by Django 5.0.14 on 2025-11-26 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_add_access_jti_to_usersession'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_completed_onboarding',
            field=models.BooleanField(default=False, verbose_name='completed onboarding'),
        ),
    ]
