# Generated by Django 5.0.14 on 2025-11-26 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_add_onboarding_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dashboard_settings',
            field=models.JSONField(blank=True, default=dict, verbose_name='dashboard settings'),
        ),
    ]
