# Generated by Django 5.0.14 on 2025-11-24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillEndorsement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('endorsed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_endorsements', to=settings.AUTH_USER_MODEL, verbose_name='endorsed by')),
                ('user_skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='endorsements', to='skills.userskill', verbose_name='user skill')),
            ],
            options={
                'verbose_name': 'skill endorsement',
                'verbose_name_plural': 'skill endorsements',
                'ordering': ['-created_at'],
                'unique_together': {('user_skill', 'endorsed_by')},
            },
        ),
    ]
