# Generated by Django 5.0.14 on 2025-11-23 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_change_content_to_jsonfield'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsattachment',
            options={'ordering': ['order', 'uploaded_at'], 'verbose_name': 'news attachment', 'verbose_name_plural': 'news attachments'},
        ),
        migrations.AddField(
            model_name='newsattachment',
            name='is_cover',
            field=models.BooleanField(default=False, verbose_name='is cover image'),
        ),
        migrations.AddField(
            model_name='newsattachment',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='order'),
        ),
        migrations.AddField(
            model_name='newsattachment',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='news/thumbnails/', verbose_name='thumbnail'),
        ),
    ]
