# Generated by Django 5.0.14 on 2025-11-23 20:44

from django.db import migrations, models


def set_published_status(apps, schema_editor):
    """Set published status for existing published news."""
    News = apps.get_model('news', 'News')
    News.objects.filter(is_published=True).update(status='published')


def reverse_published_status(apps, schema_editor):
    """Reverse: no action needed."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_add_gallery_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='publish_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='publish at'),
        ),
        migrations.AddField(
            model_name='news',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('published', 'Published')], default='draft', max_length=20, verbose_name='status'),
        ),
        migrations.RunPython(set_published_status, reverse_published_status),
    ]
