# Generated by Django 5.0.14 on 2025-11-28 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('roles', '0002_add_is_admin_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_enabled', models.BooleanField(default=False, help_text='Allow users to register themselves', verbose_name='registration enabled')),
                ('default_role', models.ForeignKey(blank=True, help_text='Role assigned to newly registered users', null=True, on_delete=django.db.models.deletion.SET_NULL, to='roles.role', verbose_name='default role for new users')),
            ],
            options={
                'verbose_name': 'site settings',
                'verbose_name_plural': 'site settings',
            },
        ),
    ]
